--AK47 OPTION SCRIPT

local module = {
	
	--NON-MELEE WEAPONS
	AUTOMATIC = true,
	HITSCAN = true,
	
	BASE_DAMAGE = 27,
	HEADSHOT_MULTIPLIER = 3.88,
	
	ACCURACY = 20, --1 = completely accurate
	FIRE_RATE = .119,
	MAGAZINE_SIZE = 30,
	TOTAL_AMMO = 90,
	RELOAD_TIME = 2,
	
	FIRE_SOUND_DISTANCE = 1000,
	BULLET_TRAVEL_SPEED = 750,
	BULLET_TRAVEL_LENGTH = 1000,
	
	MOVEMENT_INACCURACY = 40, --leave at 1 for no inacc
	JUMPING_INACCURACY = 100,
	COUNTER_STRAFE_INCREMENT = 3,
	
	FIRE_SWAY_SPEED = 5,
	FIRE_SWAY_X = 0.033,
	FIRE_SWAY_Y = 0.033,
	FIRE_SWAY_Z = 0.055,
	FIRE_RECOVERY_SWAY_X = 0.033,
	FIRE_RECOVERY_SWAY_Y = 0.033,
	FIRE_RECOVERY_SWAY_Z = 0.033,
	
	RELOAD_SWAY_X = 1,
	RELOAD_SWAY_Y = 1,
	RELOAD_SWAY_Z = 1,
	
	--RECOIL
	
	
	--MELEE WEAPONS
	SWINGSPEED = 1,
	SWING_SWAY = 1,
	
	--ALL WEAPONS
	MELEE = false,
	MASS = 9,

	WALK_SWAY = 1,
	PULLOUT_SWAY = 1,
	EQUIP_SWAY_SPEED = 2,
	EQUIP_SWAY_DOWN_DELAY = .3,
	
	SKINS = true,
	STATS = true,
	
}

return module
